name: Deploy Staging

on:
  workflow_dispatch:
    branches: ['main']

jobs:
  deploy:
    uses: Virtual-Finland-Development/status-admin/.github/workflows/deployment.yml@main
    with:
      deployment_stage: staging
    secrets: inherit
