name: Deploy Dev

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    uses: Virtual-Finland-Development/status-admin/.github/workflows/deployment.yml@main
    with:
      deployment_stage: dev
    secrets: inherit
